spring:
  application:
    name: MajiangApplicationBackend
  datasource:
    url: jdbc:mysql://${majiang-calculator.host}/${majiang-calculator.database}
    username: root
    password: dhqxiao159
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB


majiang-calculator:
  host: 127.0.0.1
  database: majiang_calculator
